# GitHub issue label data file for this project (YAML)
issuelabel_1: color1: "#ffffff" title1: "wontfix" description1: "This will not be worked on"
issueLabel_2: color2: "#d876e3" title2: "question" description2: "Further information is requested"
issueLabel_3: color3: "#e4e669" title3: "invalid" description3: "This doesn't seem right"
issueLabel_4: color4: "#008672" title4: "help wanted" description4: "Extra attention is needed"
issueLabel_5: color5: "#7057ff" title5: "good first issue" description5: "Good for newcomers"
issueLabel_6: color6: "#a2eeef" title6: "enhancement" description6: "New feature or request"
issueLabel_7: color7: "#cfd3d7" title7: "duplicate" description7: "This issue or pull request already exists"
issueLabel_8: color8: "#0075ca" title8: "documentation" description8: "Improvements or additions to documentation"
issueLabel_9: color9: "#d73a4a" title9: "bug" description9: "Something isn't working"
issueLabel_10: color10: "#149120" title10: "XBox audio" description10: "Issues related to Microsoft XBox audio"
issueLabel_11: color11: "#80d2e5" title11: "Windows 2000 audio" description11: "Issues related to Windows 2000 audio"
issueLabel_12: color12: "#c5def5" title12: "Windows 98 audio" description12: "Issues related to Windows 98 audio"
issueLabel_13: color13: "#c5def5" title13: "Windows 95 audio" description13: "Issues related to Windows 95 audio"
issueLabel_14: color14: "#1d76db" title14: "Windows 7 audio" description14: "Issues related to Windows 7 audio"
issueLabel_15: color15: "#1d76db" title15: "Windows 3.1 audio" description15: "Issues related to Windows 3.1 audio"
issueLabel_16: color16: "#0052cc" title16: "Windows XP audio" description16: "Issues related to Windows XP audio"
issueLabel_17: color17: "#c2e0c6" title17: "Windows Vista audio" description17: "Issues related to Windows Vista audio"
issueLabel_18: color18: "#befc67" title18: "Windows NT 5 audio" description18: "Issues related to Windows NT 5.0 audio"
issueLabel_19: color19: "#4a87e2" title19: "Windows NT 4 audio" description19: "Issues related to Windows NT 4.0 audio"
issueLabel_20: color20: "#5319e7" title20: "Window Media Player audio" description20: "Issues related to Windows Media Player audio"
issueLabel_21: color21: "#d93f0b" title21: "Ubuntu audio" description21: "Issues related to Ubuntu audio"
issueLabel_22: color22: "#5defef" title22: "SEGA Audio" description22: "Issues related to SEGA audio"
issueLabel_23: color23: "#000080" title23: "Samsung audio" description23: "Issues related to Samsung audio."
issueLabel_24: color24: "#FF0000" title24: "⚠️ Ring 0 security issue (URGENT) ⚠️" description24: "For security flaws when the program gets root access (UNIX)"
issueLabel_25: color25: "#ffff00" title25: "Program functionality" description25: "For issues related to program functionality."
issueLabel_26: color26: "#006b75" title26: "PlayStation audio" description26: "Issues related to Sony PlayStation audio"
issueLabel_27: color27: "#FF0000" title27: "Nintendo audio" description27: "Issues related to Nintendo audio."
issueLabel_28: color28: "#5319e7" title28: "MacOS audio" description28: "Issues related to Classic MacOS, MacOS X, and OS X audio"
issueLabel_29: color29: "#f4be9a" title29: "Audio upload needed" description29: "For audio that has not yet been uploaded"
issueLabel_30: color30: "#ffe4cc" title30: "Audio conversion" description30: "For audio that needs to be converted into another format."
# Users can also create their own issue labels, and customize the color, title, and description
# issueLabel_31: color31: "#000000" title31: "void" description31: "not yet created"
# No known limit on # of issue labels
# End of file
